[project]
name = "sinad-meter"
version = "0.1.0"
description = "A software SINAD meter"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11"
dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "pydwf",
    "pyserial>=3.5",
    "python-vxi11>=0.9",
    "pyvisa",
    "pyvisa-py>=0.8.1",
    "registries",
    "scipy",
    "sounddevice",
]

[tool.uv]
package = false
